### ISSUE TITLE
Console error when loggin 

### ISSUE THREAD

**Issue by xLasttDev** [Phibonacci/Total-Immersive-Chat-System#11]
`function: GetMessageType -- file: ISChat.lua line # 1203 | MOD: Total Immersive Chat System
function: addLineInChat -- file: ISChat.lua line # 1237 | MOD: Total Immersive Chat System
function: addLineToChat -- file: utils.lua line # 99 | MOD: Player Connection Message
function: doDisconnect -- file: utils.lua line # 40 | MOD: Player Connection Message
function: onServerCommand -- file: MainClient.lua line # 15 | MOD: Player Connection Message
java.lang.RuntimeException: Object tried to call nil in GetMessageType
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
    at zombie.network.GameClient.receiveClientCommand(GameClient.java:1513)
    at zombie.network.PacketTypes$PacketType.onMainLoopHandlePacketInternal(PacketTypes.java:1028)
    at zombie.network.GameClient.mainLoopHandlePacketInternal(GameClient.java:644)
    at zombie.network.GameClient.mainLoopDealWithNetData(GameClient.java:621)
    at zombie.network.GameClient.update(GameClient.java:431)
    at zombie.GameWindow.logic(GameWindow.java:232)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by Phibonacci** [comment]
I am guessing you are using a mod that is directly calling `ISChat.addLineInChat` with its own `message` object that does not implement a `toString` method.

The mod should implement all the `message` public methods properly to be compatible with other mods.

**Comment by Phibonacci** [comment]
I am closing the issue as it is not related to TICS. However I pushed an update recently that should allow TICS to work with more half baked mods that failed to replicate the java message object.
