### ISSUE TITLE
error when other mod send notification in chat

### ISSUE THREAD

**Issue by IceBearGanbate** [Phibonacci/Total-Immersive-Chat-System#9]
function: GetMessageType -- file: ISChat.lua line # 1203 | MOD: Total Immersive Chat System
function: addLineInChat -- file: ISChat.lua line # 1237 | MOD: Total Immersive Chat System
function: addLineToChat -- file: utils.lua line # 99 | MOD: Player Connection Message
function: doConnect -- file: utils.lua line # 11 | MOD: Player Connection Message
function: onServerCommand -- file: MainClient.lua line # 7 | MOD: Player Connection Message
java.lang.RuntimeException: Object tried to call nil in GetMessageType
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)

error whenever a mod send a notification to chat, example, mod udderly up to date that send server restarting notification because of mod update
or playerconnectedmessage when sending connected player notif to chat

mod version 1.2.0

**Comment by Phibonacci** [comment]
I made a commit specifically to support UdderlyUpToDate, so I was hopping 1.2.0 would work. Are you sure this mod is responsible?

However I do expect *playerconnectedmessage* to bug as I did not try to support it.

I will try to find time to check if there is a way to support more mods.

**Comment by IceBearGanbate** [comment]
thanks for replying.
i think the error comes from *playerconnectedmessage*  mod when it send
message to chat about a player connected or disconnected

i really appreciate it if you can add more support for other mods

cheers

**Comment by Phibonacci** [comment]
I modified TICS to be more tolerant to mods with badly formatted message objects. Hopefully it will be able to support most of them.

**Comment by IceBearGanbate** [comment]
Awesome, thanks for the update!
